syntax = "proto3";

package volontariapp.post;

import "volontariapp/post/post.requests.proto";
import "volontariapp/post/post.responses.proto";



service PostService {
  rpc GetPost (GetPostRequest) returns (GetPostResponse) {}
  rpc ListPosts (ListPostsRequest) returns (ListPostsResponse) {}
  rpc CreatePost (CreatePostRequest) returns (CreatePostResponse) {}
  rpc UpdatePost (UpdatePostRequest) returns (UpdatePostResponse) {}
  rpc DeletePost (DeletePostRequest) returns (DeletePostResponse) {}
}
