syntax = "proto3";

package volontariapp.event;

import "volontariapp/event/event.requests.proto";
import "volontariapp/event/event.responses.proto";


service EventService {
  rpc GetEvent (GetEventRequest) returns (GetEventResponse) {}
  rpc ListEvents (ListEventsRequest) returns (ListEventsResponse) {}
  rpc CreateEvent (CreateEventRequest) returns (CreateEventResponse) {}
  rpc UpdateEvent (UpdateEventRequest) returns (UpdateEventResponse) {}
  rpc DeleteEvent (DeleteEventRequest) returns (DeleteEventResponse) {}
}
