syntax = "proto3";

package volontariapp.event;

import "volontariapp/event/event.query.proto";
import "volontariapp/event/event.command.proto";
import "volontariapp/event/event.responses.proto";

service EventCommandService {
  rpc CreateEvent (CreateEventCommand) returns (EventResponse) {}
  rpc UpdateEvent (UpdateEventCommand) returns (EventResponse) {}
  rpc ChangeEventState (ChangeEventStateCommand) returns (EventResponse) {}
  rpc ManageRequirements (ManageRequirementCommand) returns (ActionSuccessResponse) {}
}

service EventQueryService {
  rpc GetEvent (GetEventQuery) returns (EventResponse) {}
  rpc SearchEvents (SearchEventsQuery) returns (ListEventsResponse) {}
  rpc ListRequirements (ListRequirementsQuery) returns (RequirementListResponse) {}
}

service TagService {
  rpc GetTags (GetTagsQuery) returns (TagListResponse) {}
  rpc CreateTag (CreateTagCommand) returns (ActionSuccessResponse) {}
}
